name: generate-directory-tree
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*'
      - '!README.md'
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run tree generator
        run: python generate_tree.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --cached --quiet || git commit -m 'chore: update README.md with directory tree [auto]'
          git push
