name: typst-build
run-name: Build Typst Documents
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.pdf'
jobs:
  build-typst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Typst
        run: |
          curl -L https://github.com/typst/typst/releases/download/v0.13.1/typst-x86_64-unknown-linux-musl.tar.xz -o typst.tar.xz
          tar -xf typst.tar.xz
          sudo mv typst-x86_64-unknown-linux-musl /usr/local/bin/typst
      - name: Find and build all .typ files
        run: |
          find . -type f -name '*.typ' | while read typfile; do
            pdffile="${typfile%.typ}.pdf"
            typst compile "$typfile" "$pdffile"
          done
      - name: Commit and push PDFs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add '*.pdf'
          git diff --cached --quiet || git commit -m 'chore: build PDFs from Typst sources [auto]'
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
